import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: {
    default: "NJS Basics",
    template: "%s | Basics",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <header>
          <div className="p-2 bg-amber-400 mb-4 flex justify-center">
            <p><Link href="/">Home</Link></p>
          </div>
        </header>
        <div className="grow h-full border border-red-500">
          {children}
        </div>
        <footer className="p-2 bg-amber-400 mt-4 flex justify-center">
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
